### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by bugaevc** [chergert/hello#10]
Would you be interested in Objective-C example using [CoreGTK](https://www.tylerburton.ca/projects/coregtk/)?

Things that make it not-so-great include: 

- Objective-C is not very Linux-friendly
- CoreGTK supports GTK+ version 3.18
- You need to build CoreGTK yourself to use it

**Comment by chergert** [comment]
Is perl great? I think not. :) Feel free to put together a PR and add a README.md to the directory if setup is extra weird.
